name: SocialMedia
version: 1.1
author: TastischerGamer
main: me.TastischerGamer.SocialMedia.main.SocialMediaPlugin

commands:
   SocialMediaManager:
      description: Erstelle / Entferne einen Command!
      Usage: /SocialMediaManager help
      aliases: [smm, socialmedia] 
